---
language: python

sudo: false

python:
  - 3.4

install:
  - pip install sphinx

script:
  - make html

notifications:
  irc:
    channels:
      - "irc.freenode.org##python-code-quality"
    use_notice: true
    skip_join: true
